logging:
  level:
    org.springframework.core.env: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${POD_IP}:${server.port}
    hostname: user-service
    prefer-ip-address: false 
    ip-address: ${POD_IP}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
